name: "Release 'master' branch"

permissions:
  contents: write

on:
  push:
    branches: ["master"]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: "ubuntu-22.04"
    strategy:
      matrix:
        target:
          # - aarch64-apple-darwin
          # - arm-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
          echo "CARGO_VERSION=$(cargo -V | cut -d " " -f 2)" >> "$GITHUB_ENV"
      - uses: actions/cache@v3
        with:
          key: cargo-${{ env.CARGO_VERSION }}-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/
            target/
      - run: cargo install cross@^0.2
      - run: |
          cross build --release --target ${{ matrix.target }}
          METADATA="$(cargo metadata --format-version=1 --no-deps)"
          BINS="$(jq -r '.packages[].targets[].name' <<< "$METADATA")"
          for bin in ${BINS}; do
            mkdir -p "artifact"
            (cd "target/${{ matrix.target }}/release/" && tar cz "${bin}") > "artifact/${bin}-${{ matrix.target }}.tar.gz"
          done
      - uses: "actions/upload-artifact@v3"
        with:
          path: "artifact/*"
  release:
    needs: "build"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/download-artifact@v3"
        with:
          name: "artifact"
          path: "artifact"
      - uses: "actions/github-script@v6"
        with:
          script: |
            const script = require('.github/script/release.js')
            await script({github, context, core});
