name: "Release 'master' branch"

permissions:
  contents: write

on:
  push:
    branches: ["master"]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: "ubuntu-22.04"
    strategy:
      matrix:
        target:
          # - aarch64-apple-darwin
          # - arm-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
    env:
      CROSS_VERSION: "0.2.4"
    steps:
      - run: |
          sudo apt-get install -y --no-install-recommends podman jq
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ env.CROSS_VERSION }}-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            ~/.cargo/git/
            target/
      - run: |
          cargo install cross@${{ env.CROSS_VERSION }}
      - run: |
          cross build --release --target ${{ matrix.target }}
          cp "target/${{ matrix.target }}/release/release-test" release-test-${{ matrix.target }}
      - uses: "actions/upload-artifact@v3"
        with:
          path: "release-test-${{ matrix.target }}"
  release:
    needs: "build"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/download-artifact@v3"
        with:
          name: "artifact"
          path: "artifact"
      - uses: "actions/github-script@v6"
        with:
          script: |
            const script = require('.github/script/release.js')
            await script({github, context, core});
