name: "Release 'master' branch"

on:
  push:
    branches: ["master"]
  workflow_dispatch: {}

jobs:
  release:
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/github-script@v6"
        with:
          script: |
            const script = require('.github/script/release.js')
            await script({github, context, core});
