name: "Release 'master' branch"

on:
  push:
    branches: ["master"]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: "ubuntu-22.04"
    strategy:
      matrix:
        target:
          # - aarch64-apple-darwin
          # - arm-unknown-linux-gnueabihf
          - aarch64-unknown-linux-gnu
          - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - run: |
          sudo apt-get install -y --no-install-recommends podman
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          cargo install cross
          cross build --release --target ${{ matrix.target }}
          cp target/release/toml2json toml2json-${{matrix.target }}
      - uses: "actions/upload-artifact@v3"
        with:
          path: "toml2json"
  release:
    needs: "build"
    runs-on: "ubuntu-22.04"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/download-artifact@v3"
        with:
          name: "artifact"
          path: "artifact"
      - uses: "actions/github-script@v6"
        with:
          script: |
            const script = require('.github/script/release.js')
            await script({github, context, core});
